// AUTO-GENERATED by scripts/scan-plugins.mjs — do not edit manually
import type { MyWatchPlugin } from '@mywatch/plugin-sdk'
import plugin0 from 'mywatch-plugin-youtube'

export const PLUGINS: MyWatchPlugin[] = [plugin0]
