#!/usr/bin/env node
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const pluginsRoot = path.resolve(__dirname, '../../../plugins')
const registryPath = path.resolve(__dirname, '../src/plugins/registry.ts')
const manifestPath = path.resolve(__dirname, '../src/plugins/.plugins-manifest.json')

const plugins = []

if (fs.existsSync(pluginsRoot)) {
  for (const entry of fs.readdirSync(pluginsRoot)) {
    const pkgPath = path.join(pluginsRoot, entry, 'package.json')
    if (!fs.existsSync(pkgPath)) continue
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'))
      if (pkg?.mywatch?.id && pkg.name) {
        plugins.push({ name: pkg.name, id: pkg.mywatch.id })
      }
    } catch {
      // skip malformed package.json
    }
  }
}

// Write registry.ts
const importLines = plugins
  .map((p, i) => `import plugin${i} from '${p.name}'`)
  .join('\n')

const registryContent = `// AUTO-GENERATED by scripts/scan-plugins.mjs — do not edit manually
import type { MyWatchPlugin } from '@mywatch/plugin-sdk'
${importLines}

export const PLUGINS: MyWatchPlugin[] = [${plugins.map((_, i) => `plugin${i}`).join(', ')}]
`

fs.mkdirSync(path.dirname(registryPath), { recursive: true })
fs.writeFileSync(registryPath, registryContent)

// Write manifest for next.config.mjs to consume
fs.writeFileSync(manifestPath, JSON.stringify(plugins, null, 2))

if (plugins.length === 0) {
  console.log('[scan-plugins] No plugins found.')
} else {
  console.log(`[scan-plugins] Found ${plugins.length} plugin(s): ${plugins.map(p => p.name).join(', ')}`)
}
